sudo: required
services:
  - docker


before_install:
  - docker build -t szt/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true szt/docker-react npm run test -- --coverage



deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-713603760360"
  bucket_path: "docker-react"
  

  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY




# DockerReact-env.eba-5uhuae2p.us-east-1.elasticbeanstalk.com     